version: '3.8'

services:

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:2.24.4
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.44.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - eureka

  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.2
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    depends_on:
      - prometheus

  config-server-db:
    container_name: config-server-db
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: configs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  eureka:
    container_name: eureka
    build:
      context: ./
      dockerfile: docker/Dockerfile-eureka
    restart: always
    ports:
      - "8761:8761"

  config-server:
    container_name: config-server
    build:
      context: ./
      dockerfile: docker/Dockerfile-config-server
    restart: always
    environment:
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
      DB_URL: jdbc:mysql://config-server-db:3306/configs?serverTimezone=UTC
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8888:8888"
    depends_on:
      - eureka
      - config-server-db

  api-gateway:
    container_name: api-gateway
    build:
      context: ./
      dockerfile: docker/Dockerfile-api-gateway
    restart: always
    environment:
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
    ports:
      - "8078:8078"
    depends_on:
      - eureka

  bank:
    container_name: bank
    build:
      context: ./
      dockerfile: docker/Dockerfile-bank
    restart: always
    environment:
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
    ports:
      - "8080:8080"
    depends_on:
      - zipkin
      - prometheus
      - config-server

  credit-bureau:
    container_name: credit-bureau
    build:
      context: ./
      dockerfile: docker/Dockerfile-credit-bureau
    restart: always
    environment:
      EUREKA_URL: ${EUREKA_URL}
      ZIPKIN_URL: ${ZIPKIN_URL}
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
      - prometheus
      - config-server