server:
  port: 8078

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank
          uri: lb://bank
          predicates:
            - Path=/bank/api/**
          filters:
            - RewritePath=/bank/(?<path>.*), /$\{path}
        - id: credit-bureau
          uri: lb://credit-bureau
          predicates:
            - Path=/credit-bureau/api/**
          filters:
            - RewritePath=/credit-bureau/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0