scrape_configs:
  - job_name: eureka
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://eureka:8761/eureka
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application