{
 "title": "Request Rates",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests from API Gateway to Bank and Credit Bureau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{application=\"API-GATEWAY\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Requests from Bank to Credit Bureau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_client_requests_seconds_count{application=\"BANK\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests to Credit Bureau",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"CREDIT-BUREAU\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests to Config Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"CONFIG-SERVER\"}[$__rate_interval])"
    }
   ]
  }
 ]
}