FROM maven:3.8.4-openjdk-17-slim AS build
COPY eureka/src /home/app/eureka/src
COPY eureka/pom.xml /home/app/eureka/pom.xml
COPY pom.xml /home/app/pom.xml
RUN mvn clean package -P eureka -f /home/app/pom.xml -DskipTests -Dcheckstyle.skip

FROM openjdk:17.0.1-jdk-slim
COPY --from=build /home/app/eureka/target/*.jar /usr/local/lib/app.jar
ENTRYPOINT java -jar /usr/local/lib/app.jar